### ISSUE TITLE
Discussion: Retry ChannelMessage if processed between channel close and ShutdownSignal

### ISSUE THREAD

**Issue by timcharper** [thenewmotion/akka-rabbitmq#12]
After thinking about this for some time, it occurred to me that solution I'd submitted doesn't entirely solve the problem, and adds significant complexity. The probability is small, but the message still may not be received if RabbitMQ-server is restarted between the time the message was written to the network and the time that RabbitMQ-server read it.

Thus, it's leaky, and you can't rely on it. I think a better approach is to use `PublisherConfirms`, anyway. Then, detect when a connection is broken, and republish anything that has not yet been confirmed. My implementation can be seen here: https://github.com/SpinGo/op-rabbit/blob/master/core/src/main/scala/com/spingo/op_rabbit/ConfirmedPublisherActor.scala

This is the patch I think we should consider rolling back:

https://github.com/thenewmotion/akka-rabbitmq/commit/c8a64ac91ae9f6a0e3217a1e61c965fd07a62fc8

Sorry for submitting a leaky solution.

**Comment by reinierl** [comment]
If I understand it correctly, change c8a64ac still makes messages likelier to arrive for users not using publisher confirms, right?

(I was away for a couple of weeks, but responsive again now)

**Comment by timcharper** [comment]
It does, yes. And, if you are using a transaction, you are guaranteed up to the retry count, since the function will either succeed and the message is delivered, or fail, and the message is not

**Comment by reinierl** [comment]
So then I'm just leaving the code in there.
