### ISSUE TITLE
URI scheme in RichConnectionFactory is hardcoded

### ISSUE THREAD

**Issue by zackangelo** [thenewmotion/akka-rabbitmq#17]
https://github.com/thenewmotion/akka-rabbitmq/blob/master/src/main/scala/com/thenewmotion/akka/rabbitmq/package.scala#L28

**Comment by reinierl** [comment]
I'm busy with the day job right now, but patches are welcome of course!

**Comment by sarveshseri** [comment]
@zackangelo What possible use-cases do you propose ?

**Comment by reinierl** [comment]
Still no use cases, so closing.
