### ISSUE TITLE
ChannelActor stuck in Disconnected state after actor restart

### ISSUE THREAD

**Issue by nikitapecasa** [thenewmotion/akka-rabbitmq#23]
As for solution - the simplest way for me is to override postRestart() and ask parent for a new channel (connectionActor ! ProvideChannel). 
But it looks like this code should be in the library, what do you think?

**Comment by reinierl** [comment]
I agree. I can do this tomorrow I think but pull requests are always welcome too ofc :)

**Comment by nikitapecasa** [comment]
Ok, here is pull request
https://github.com/thenewmotion/akka-rabbitmq/pull/24

**Comment by reinierl** [comment]
Now fixed in version 2.3.

**Comment by nikitapecasa** [comment]
Thanks! Just upgraded to 2.3, everything seems to be ok.
