### ISSUE TITLE
Publish to maven central

### ISSUE THREAD

**Issue by timcharper** [thenewmotion/akka-rabbitmq#25]
Hey guys, I'm moving op-rabbit to be published via Maven central instead of s3. Would you like to do the same? Before, I was publishing a copy of akka-rabbitmq and op-rabbit to my own repo in order to prevent people from having to add two resolvers to use op-rabbit.

Let me know if / how I can help.

**Comment by wpc009** [comment]
Aha, that's why I can use `op-rabbit`'s `akka-rabbitmq` version 2.2, but I can't resolve 2.3.
Can I suggest at least push to JCenter?

**Comment by fedgehog** [comment]
Published 3.0.0-RC1 to OSS sonatype. Should be on maven central soon.
