### ISSUE TITLE
Working with a RabbitMQ cluster?

### ISSUE THREAD

**Issue by DougC** [thenewmotion/akka-rabbitmq#3]
Is there a way to configure akka-rabbitmq to deal with a cluster? As I understand clustering we would have multiple hosts to connect to. Can akka-rabbitmq handle failover from one host to another?

**Comment by abhihdr03** [comment]
DougC can you clarify the below points here:
wouldn't it be a new connection when newConnection  with array of Address  is called, how the original actor will use this new connection, How the re connection part will work?

Thanks in advance.
