### ISSUE TITLE
Prematurely sending messages

### ISSUE THREAD

**Issue by Hajto** [thenewmotion/akka-rabbitmq#31]
I have created simple wrapper around akka-rabbitmq.

```
class Rabbiter(val actorSystem: ActorSystem, exchange:String = "smartoffice") {
  private val factory = new ConnectionFactory()
  private val connectionActor: ActorRef = actorSystem.actorOf(ConnectionActor.props(factory))
  private val outPutChannel = createChanel

  def createChanel = connectionActor.createChannel(ChannelActor.props { (channel, ref) =>
    channel.exchangeDeclare(exchange,"topic")
  })

  def sendMessage(channel: ActorRef, routingKey: String, message: String) = 
    channel ! ChannelMessage({ channel =>
      channel.basicPublish(exchange, routingKey, null, message.getBytes)
  })

  def sendMessage(routingKey: String, message: String): Unit = 
    sendMessage(outPutChannel, routingKey, message)

  ....
}
```

Which is based on your readme. But if I instantiate connection and immediately send message I get such error message.

`15:46:46.893 [rabbitNetwork-akka.actor.default-dispatcher-2] DEBUG c.t.akka.rabbitmq.ChannelActor - in Disconnected received ChannelMessage(<function1>,true): dropping message <function1>`

Example code:

```
val channel = new Rabbiter(context.system)
    channel.sendMessage("rooms.events.requestReplay", "")
    channel.listenTo("rooms.events.spawnRooms") { payload =>
      val readValues = read[List[Int]](payload)
      readValues.foreach(spawnChild)
    }
```

Was usually resulting in not sending any message and getting that error. But when we put `Thread.sleep` for testing purposes it worked. So I guess messages were sent prior to successful connection.

**Comment by reinierl** [comment]
There is a StashUntilChannel trait that takes care of this. See https://github.com/thenewmotion/akka-rabbitmq/blame/bd6f1920be5b9cfdd3fa20a61776eb94702a672c/src/main/scala/com/thenewmotion/akka/rabbitmq/StashUntilChannel.scala .

**Comment by nikitapecasa** [comment]
Snippet you need (from readme):

channelActor ! ChannelMessage(publish, dropIfNoChannel = false)
