### ISSUE TITLE
ChannelActor does not queue functions which throw exceptions when connected to RabbitMQ

### ISSUE THREAD

**Issue by Yaneeve** [thenewmotion/akka-rabbitmq#8]
It seems to me that the following code is problematic:

 ```when(Connected) {
...```

    case Event(ChannelMessage(f, _), Connected(channel)) =>
      safe(f(channel)) match {
        case None =>
          reconnect(channel)
          goto(Disconnected) using InMemory()
        case _ => stay()
      }

the function ```f(channel)``` does not get queued for re-invocation upon exception (i.e., when ```None``` is encountered)

would it not be better to code something like:

    case Event(ChannelMessage(f, _), Connected(channel)) =>
      safe(f(channel)) match {
        case None =>
          reconnect(channel)
          goto(Disconnected) using InMemory(Queue(f))
        case _ => stay()
      }

Or am I missing the intent of the code?

**Comment by reinierl** [comment]
Hmm yes. Although we probably don't want to requeue f on just any exception to prevent the library from getting stuck in a retry loop. Only if we can be sure that the error was a disconnect, we should retry f.

This is especially nasty if f contains exception handling in the user code that catches connection exceptions and re-throws them as something else.

**Comment by Yaneeve** [comment]
Thanks for your reply!

The way I see it is that 4 options present themselves:
1.  Leave the library as is. This means that "unsafe" functions ```f(channel)``` get dropped. This would mean that the library stays stable, but in my opinion this behavior should be explicitly documented.

2.  Blindly queue any offending ```f``` functions in the hope that they are not inherently flawed. This would mean that it is the responsibility of user code, not the library to take care of itself and not loop on the same exception for ever. This is a bit like some Java API documenting a NullPointerException on null input.

3.  Queue only functions ```f``` that throw an IOException. This needs to be documented of course. It would also mean the reworking of the ```safe``` function. This approach posits that IOException come from the underlying rabbitmq java library and not from user code and so attempts to rerun the function ```f``` at a later time holding the rabbitmq library at fault for the exception. On the other hand any other exception is dangerous user code which the library would like to protect itself from.

4.  Same as 3 above except the even IOExceptions are not blindly requeued. Each offending function ```f``` would be queued along a retry counter (configurable or whatnot) and get requeued only as many times as retrying is allowed - 3 for example.

Please let me know how you intend to progress...
IMHO options 3 or 4 are best.

**Comment by t3hnar** [comment]
Personally I can see two problems:
* we currently do not retry `f` that throwed exception, although there is a chance of `f` is not a root cause
* we need a better way to distinguish `RabbitMQ` exception from user exceptions, including `IOException`

I propose to add `retry` counter, for example `2` as default for `f` and enqueue it on `RabbitMQ` exception

Is anyone eager to make a pull request? ;)

**Comment by fedgehog** [comment]
Correct me if I'm wrong, but `ChannelActor` reinvents RMI in Akka.
I'd rather investigated the way to make it message oriented, than built on top supporting code that allows us even easier to shoot ourselves in the foot.

**Comment by t3hnar** [comment]
you are right, and it was considered and even discussed somewhere on akka forum...
so in short it is huge amount of work to cover RabbitMQ api. Btw, there is scala project that does this for some basic operations.

**Comment by fedgehog** [comment]
I propose to 
- leave things as they are but add documentation with HUGE warning :)
- look at https://github.com/ScalaConsultants/reactive-rabbit and other libs that couple Akka & RabbitMQ and decide whether we want to support some basic subset of RMQ API, dare to tackle broader one or ...

**Comment by reinierl** [comment]
> Op 29 jan. 2015, om 22:03 heeft Maxim Fedorov <notifications@github.com> het volgende geschreven:
> 
> I propose to
> 
> leave things as they are but add documentation with HUGE warning :)
> look at https://github.com/ScalaConsultants/reactive-rabbit <https://github.com/ScalaConsultants/reactive-rabbit> and other libs that couple Akka & RabbitMQ and decide whether we want to support some basic subset of RMQ API, dare to tackle broader one or …

I have recently investigated some different Akka - RabbitMQ libraries and judged that this was a pretty good one :)

Its most useful feature is that it transparently does reconnection on failure. Even though, it cannot guarantee that no message is lost, because that is inherently impossible in the presence of hardware failure, buggy third-party software etc. So I will go for the “HUGE warning”.

If you want to be really sure that your message was successfully processed by the other side of the connection, you have to use acknowledgements or confirms.

—
Reinier=

**Comment by Yaneeve** [comment]
It is my opinion that this library is very well engineered to handle a lost connection. There is only one limitation, and that is the "bug" discussed in this thread. I think that a HUGE warning should definitely be added, but I think that some sort of best effort should also be made. It is true that the library has no way of recognizing a true RabbitMQ exception vs user code exceptions. That being the case, I propose another strategy, roll the responsibility of "marking" such exceptions. We could define a  *UserCodeDetectedRabbitMQException* type and only requeue the "offending" function ```f``` that throws such an exception (with or without retries). This would mean that the library takes care of itself on any exception IO or otherwise unless explicitly receiving this *signal* from the user. Moreover, this need not be an exception, this is just an implementation detail, as long as the user code has a way to let the library know that it is not the fault of the user code but of the underlying RabbitMQ library.

I think that this would give us the best of both worlds, stability and recoverability (where the order of submitted messages is not changed.)

With regards the pull request, first, I am a scala novice, second my organization, though it has need of this "defect" fix, has not allocated me the time in the upcoming month (and I do not know if I will have personal time to "fix" it). Lastly, my organization will eventually require a fix, and so, even if a pull request is not accepted, we will most likely fork the project and "fix" the issue, when the time comes...

**Comment by reinierl** [comment]
I changed the README and included an example file showing the use of confirms.
